kind: Deployment
apiVersion: apps/v1
metadata:
    labels:
        app: di-website
        stack: frontend
        source: di
    name: di-website
    namespace: di
spec:
    replicas: 3
    selector:
        matchLabels:
            run: di-website
    template:
        metadata:
            labels:
                app: di-website
                run: di-website
                source: di
        spec:
            containers:
                -   image: 465848653329.dkr.ecr.us-west-2.amazonaws.com/di-website
                    name: di-website
                    ports:
                        -   name: web
                            containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
    labels:
        app: di-website-service
    name: di-website-service
    namespace: di
spec:
    selector:
        source: di
        app: di-website
    ports:
        -   name: web
            protocol: TCP
            port: 30201
            targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    name: di-website-ingress
    namespace: di
spec:
    rules:
        -   http:
                paths:
                    -   path: /di-website(/|$)(.*)
                        backend:
                            serviceName: di-website-service
                            servicePort: 30201


